package cz.xefensor.retold.behavior;

public enum RetoldAiControlOwner {
    SYSTEM,
    FOOD,
    PREDATOR_SEARCH,
    SOLO_HUNTING,
    PACK_HUNTING,
    FLEEING,
    COMBAT,
    RAIDER_ROAM,
    COMMANDER_SUPPORT,
    UNDEAD_HORDE,
    UNDEAD_RANGED,
    SPECIAL_UNDEAD,
    SWARM,
    SCAVENGER,
    HIVE_COLONY,
    AQUATIC_POD,
    NEUTRAL_WILDLIFE,
    AMPHIBIAN_FORAGER,
    AQUATIC_HELPER,
    PANDA_BAMBOO,
    SNIFFER_FORAGER,
    ARMADILLO_DEFENSE,
    TERRITORY,
    REGROUP,
    DEBUG
}
